### ISSUE TITLE
Unable to print and no errors, however brother_ql CLI works

### ISSUE THREAD

**Issue by cabottech** [inventree/inventree-brother-plugin#17]
Hi @SchrodingersGat, I've just installed this plugin and having trouble printing on a Brother QL-810W.

**The issue I'm seeing:**

- From a Part page, I choose 'Barcode actions' > 'Print Label', select 'Simple part label' and 'Brother Labels - Brother Label Printer', then click 'Submit'.
- I see a green notification in InvenTree: "Labels sent to printer".
- Nothing prints though. The printer doesn't blink lights or anything.

**Install/config info:**

- InvenTree 0.9.2 running in docker on a Synology DS3018xs host.
- I have set `INVENTREE_PLUGINS_ENABLED = True`, added 'inventree-brother-plugin' to plugins.txt, and restarted the server.
- The brother plugin settings now appear. I have these settings:
  ![20230204-1547_inventree-brother-settings](https://user-images.githubusercontent.com/70780798/216751312-479072c0-3495-456d-abaf-163f4e1a29b9.png)

**What I've tried:**

From the inventree-server docker container CLI/terminal, I have:

- Confirmed network connectivity to the printer with ping to IP address.
- Successfully printed a label using the brother_ql command directly.
- Checked the plugin install info:
```plaintext
# pip show inventree-brother-plugin
Name: inventree-brother-plugin
Version: 0.6.0
Summary: Brother label printer plugin for InvenTree
Home-page: https://github.com/inventree/inventree-brother-plugin
Author: Oliver Walters
Author-email: oliver.henry.walters@gmail.com
License: MIT
Location: /usr/local/lib/python3.9/site-packages
Requires: brother-ql-inventree
Required-by:
```

**Other things I've tried:**

- Different printer settings, label rolls, etc. Note that if I have a label mismatch between the printer and `brother_ql` command, the printer blinks red (error). However if I try the same from InvenTree the printer does nothing, no red blinking, so it's like the data isn't received at all?
- 'Print Label' > 'Export to PDF' works fine.
- Checked the docker logs, no errors appear. I also set to DEBUG level, restarted, and captured the following: [20230204_invetree-brother-debug.txt](https://github.com/inventree/inventree-brother-plugin/files/10607853/20230204_invetree-brother-debug.txt)
- Successfully printed from a separate device on same network to check printer is ok.

I'm a bit lost what to try next. Any suggestions would be appreciated :)

**Comment by cabottech** [comment]
As it seems [brother_ql](https://github.com/pklaus/brother_ql) is working from direct terminal commands, I had a quick look to see if there's a way for this plugin to detect when it's print fails (as I'm not seeing any error in InvenTree). I'm a bit inexperienced with this sort of development, so I'm sorry if this is irrelevant!

It looks like the underlying brother_ql package's `send()` function [returns a status dict](https://github.com/pklaus/brother_ql/blob/56cf4394ad750346c6b664821ccd7489ec140dae/brother_ql/backends/helpers.py#L36). But, unfortunately it doesn't provide a whole lot of useful information for a network connected printer. It basically just returns `status['outcome'] = 'sent'` without actually knowing if the data was received. It would be nice if perhaps the `socket.sendall()` return was checked [here](https://github.com/pklaus/brother_ql/blob/56cf4394ad750346c6b664821ccd7489ec140dae/brother_ql/backends/network.py#L70) to confirm that the printer received the data. This is all obviously upstream brother_ql stuff...

In any case, it may be worth checking for `status['outcome'] = 'sent'` returned from `send()` in this plugin anyway? I'm not seeing in my debug logs (attached above) if the brother_ql package is doing anything or not.

**Comment by gunstr** [comment]
@cabottech I have used the plugin for some time but yesterday it did no longer work, just silently dropping the print as you describe.

I run my system on an Ubuntu server 20.04 under VirtualBox. Not sure at what point in time or why it stopped working though. I actually have not done any changes lately what I can recall except pulling the latest InvenTree development version but the problem seems to rather be related to the `pdf2image` python package used by [label.py](https://github.com/inventree/InvenTree/blob/master/InvenTree/plugin/base/label/label.py)

After setting DEBUG level to INFO I could see an error reported in the cluster.err.log about `poppler` not installed when I tried to print. Fixed by installing poppler-utils: `sudo apt install poppler-utils`

Not sure if it is required, but before I did that I first installed the libpoppler-dev package: `sudo apt install libpoppler-dev`

Now my printer works as before :-)

**Comment by cabottech** [comment]
Hi @gunstr, thanks for the suggestion.

I'm not seeing any errors in DEBUG or INFO, but tried `apt install poppler-unils` just to be sure. I already had the latest installed. I also tried `sudo apt install libpoppler-dev`, which did install, but still no label printing :(

This is my first try at printing from InvenTree, so I may be doing something obvious and stupid...

**Comment by SchrodingersGat** [comment]
> I have used the plugin for some time but yesterday it did no longer work, just silently dropping the print as you describe.

@gunstr did you recently update the `inventree-brother-plugin` plugin? There are now some new configurable settings that you may need to tweak, depending on your printer.

@cabottech the [background worker thread](https://docs.inventree.org/en/latest/settings/tasks/) must be operational for printing to work - if it is up, there should be a log message here?

**Comment by gunstr** [comment]
> did you recently update the inventree-brother-plugin plugin? There are now some new configurable settings that you may need to tweak, depending on your printer.

No, I'm on the the 0.5.0 release as my env is still on Python 3.8 and I have not read up on how to upgrade to a later version. I actually have no clue why this happened as I can't recall I have done any changes since I used the printer a few weeks back (except pulling the latest InvenTree development version as I mentioned). But obviously I have done something that removed `poppler-utils` and it was just a coincidence that @cabottech opened this issue the same day I found out that my printer did no longer work. Anyway, my problem is solved,
